import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, CalendarDays, GraduationCap, Users } from "lucide-react";
import { PageIntro } from "@/components/layout/PageIntro";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { SectionHeader } from "@/components/ui/SectionHeader";
import { trainingPrograms } from "@/data/training-programs";

export const metadata: Metadata = { title: "VTIME", description: "VTIME is the RECCU-CAM learning platform for cooperative capability and professional development." };
export default function VtimePage() {
  return <><PageIntro eyebrow="VTIME learning platform" title="Practical learning for stronger cooperative institutions." description="A structured learning environment for governance, responsible operations, digital readiness, and member-centred service." /><Section><Container><div className="grid gap-5 sm:grid-cols-3">{[[GraduationCap,"Role-relevant","Learning organised around real institutional responsibilities."],[BookOpenCheck,"Practical","Clear modules designed to connect knowledge with daily work."],[Users,"Networked","A shared foundation for consistent practice across institutions."]].map(([Icon,title,text]) => <article key={title as string} className="rounded-3xl bg-primary-50 p-6"><Icon className="h-6 w-6 text-accent-600" /><h2 className="mt-5 font-bold text-primary-900">{title as string}</h2><p className="mt-2 text-sm leading-6 text-gray-600">{text as string}</p></article>)}</div></Container></Section><Section className="bg-[#F7FAF8]"><Container><SectionHeader eyebrow="Programme catalogue" title="Start with the capability that matters now." subtitle="Programme outlines are visible for planning. Dates, facilitators, venues, fees, and registration remain unpublished until confirmed." /><div className="mt-10 grid gap-5 lg:grid-cols-3">{trainingPrograms.map((program) => <article key={program.slug} className="rounded-3xl border border-primary-100 bg-white p-6"><p className="text-xs font-bold uppercase tracking-wider text-accent-700">{program.audience}</p><h2 className="mt-4 font-display text-xl font-bold text-primary-900">{program.title}</h2><p className="mt-3 text-sm leading-6 text-gray-600">{program.summary}</p><ul className="mt-5 space-y-2 text-sm text-gray-700">{program.modules.map(module => <li key={module} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent-500" />{module}</li>)}</ul></article>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href="/vtime/programs" className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary-800 px-5 font-bold text-white">View all programmes <ArrowRight className="h-4 w-4" /></Link><Link href="/vtime/calendar" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-primary-200 px-5 font-bold text-primary-800"><CalendarDays className="h-4 w-4" /> Training calendar</Link></div></Container></Section></>;
}
