// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // CLI/migrations bypass the pooler and connect directly — Supabase's
    // transaction-mode pooler doesn't support the advisory locks migrate needs.
    url: process.env["DIRECT_URL"],
  },
});
