import { prisma } from "@/lib/prisma";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { createTrainingProgram } from "@/app/admin/(dashboard)/operations/actions";

export default async function VtimeAdminPage() {
  const programs = await prisma.trainingProgram.findMany({ include: { _count: { select: { registrations: true } } }, orderBy: { createdAt: "desc" } });
  return <div className="space-y-7"><header><p className="text-xs font-semibold uppercase tracking-[0.14em] text-gold-strong">Training administration</p><h1 className="mt-2 font-display text-3xl font-bold text-institutional">VTIME</h1><p className="mt-2 text-slate-600">Publish verified programs and monitor registrations.</p></header><Card className="p-6"><h2 className="font-semibold text-institutional">Create training program</h2><form action={createTrainingProgram} className="mt-5 grid gap-4 sm:grid-cols-2"><input required name="title" placeholder="Program title" className="rounded-lg border border-slate-300 px-3 py-2" /><input required name="category" placeholder="Category" className="rounded-lg border border-slate-300 px-3 py-2" /><textarea required name="summary" placeholder="Program summary" className="rounded-lg border border-slate-300 px-3 py-2 sm:col-span-2" /><input required name="level" placeholder="Level" className="rounded-lg border border-slate-300 px-3 py-2" /><select name="format" className="rounded-lg border border-slate-300 px-3 py-2"><option value="">Format pending</option><option value="in-person">In person</option><option value="online">Online</option><option value="hybrid">Hybrid</option></select><input name="venue" placeholder="Venue" className="rounded-lg border border-slate-300 px-3 py-2" /><input name="capacity" type="number" min="1" placeholder="Capacity" className="rounded-lg border border-slate-300 px-3 py-2" /><label className="text-xs font-semibold text-slate-600">Start date<input name="startDate" type="date" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="text-xs font-semibold text-slate-600">End date<input name="endDate" type="date" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><button className="rounded-lg bg-institutional px-4 py-2 font-semibold text-white sm:col-span-2">Publish program</button></form></Card><section><h2 className="mb-3 font-semibold text-institutional">Programs</h2>{programs.length ? <div className="grid gap-4 md:grid-cols-2">{programs.map((program) => <Card key={program.id} className="p-5"><div className="flex justify-between gap-3"><h3 className="font-semibold text-slate-900">{program.title}</h3><Badge>{program.published ? "Published" : "Draft"}</Badge></div><p className="mt-2 text-sm text-slate-600">{program.summary}</p><p className="mt-4 text-xs text-slate-500">{program._count.registrations} registrations · {program.registrationStatus}</p></Card>)}</div> : <Card className="p-8 text-center text-sm text-slate-500">No programs have been created.</Card>}</section></div>;
}
