import { prisma } from "@/lib/prisma";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { createComplianceRecord } from "@/app/admin/(dashboard)/operations/actions";

export default async function ComplianceAdminPage() {
  const [records, affiliates] = await Promise.all([prisma.complianceRecord.findMany({ orderBy: { createdAt: "desc" } }), prisma.affiliate.findMany({ where: { isActive: true }, select: { id: true, name: true }, orderBy: { name: "asc" } })]);
  return <div className="space-y-7"><header><p className="text-xs font-semibold uppercase tracking-[0.14em] text-gold-strong">Compliance administration</p><h1 className="mt-2 font-display text-3xl font-bold text-institutional">Compliance</h1><p className="mt-2 text-slate-600">Publish editable, verified notices and required submissions. No regulatory deadlines are pre-invented.</p></header><Card className="p-6"><h2 className="font-semibold text-institutional">Publish compliance item</h2><form action={createComplianceRecord} className="mt-5 grid gap-4 sm:grid-cols-2"><input required name="title" placeholder="Title" className="rounded-lg border border-slate-300 px-3 py-2" /><input required name="category" placeholder="Category" className="rounded-lg border border-slate-300 px-3 py-2" /><textarea required name="description" placeholder="Verified guidance or submission requirement" className="rounded-lg border border-slate-300 px-3 py-2 sm:col-span-2" /><label className="text-xs font-semibold text-slate-600">Due date (optional)<input name="dueDate" type="date" className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><select name="audience" className="rounded-lg border border-slate-300 px-3 py-2"><option value="all-affiliates">All affiliates</option><option value="specific-affiliate">Specific affiliate</option></select><select name="affiliateId" className="rounded-lg border border-slate-300 px-3 py-2 sm:col-span-2"><option value="">All affiliates</option>{affiliates.map((affiliate) => <option key={affiliate.id} value={affiliate.id}>{affiliate.name}</option>)}</select><button className="rounded-lg bg-institutional px-4 py-2 font-semibold text-white sm:col-span-2">Publish item</button></form></Card><div className="space-y-3">{records.map((record) => <Card key={record.id} className="p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-gold-strong">{record.category}</p><h2 className="mt-1 font-semibold text-slate-900">{record.title}</h2></div><Badge>{record.status}</Badge></div><p className="mt-3 text-sm text-slate-600">{record.description}</p></Card>)}</div></div>;
}
