import { clerkClient } from "@clerk/nextjs/server";
import { Card } from "@/components/ui/Card";
import { APP_ROLES, ROLE_LABELS, normalizeAuthRole } from "@/lib/auth/roles";
import { updateUserAccess } from "@/app/admin/(dashboard)/operations/actions";

export default async function UsersAndRolesPage() {
  const clerk = await clerkClient();
  const { data: users } = await clerk.users.getUserList({ limit: 100, orderBy: "-created_at" });
  return <div className="space-y-6"><header><p className="text-xs font-semibold uppercase tracking-[0.14em] text-gold-strong">Super administrator</p><h1 className="mt-2 font-display text-3xl font-bold text-institutional">Users & Roles</h1><p className="mt-2 text-slate-600">Clerk remains the credential authority. Passwords are never available to administrators.</p></header><div className="space-y-4">{users.map((user) => { const role = normalizeAuthRole(user.publicMetadata.role); const name = [user.firstName, user.lastName].filter(Boolean).join(" ") || "Unnamed user"; return <Card key={user.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-semibold text-slate-900">{name}</h2><p className="mt-1 text-sm text-slate-500">{user.primaryEmailAddress?.emailAddress ?? "No primary email"}</p><p className="mt-1 text-xs text-slate-400">Last login: {user.lastSignInAt ? new Date(user.lastSignInAt).toLocaleString("en-GB") : "Never"}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${user.banned ? "bg-red-100 text-red-700" : "bg-emerald-100 text-emerald-700"}`}>{user.banned ? "Deactivated" : "Active"}</span></div><div className="mt-5 flex flex-wrap gap-3"><form action={updateUserAccess} className="flex gap-2"><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="operation" value="role" /><select name="role" defaultValue={role ?? ""} className="rounded-lg border border-slate-300 px-3 py-2 text-sm"><option value="" disabled>Select role</option>{Object.values(APP_ROLES).map((value) => <option key={value} value={value}>{ROLE_LABELS[value]}</option>)}</select><button className="rounded-lg bg-institutional px-3 py-2 text-sm font-semibold text-white">Change role</button></form><form action={updateUserAccess}><input type="hidden" name="userId" value={user.id} /><input type="hidden" name="operation" value={user.banned ? "reactivate" : "deactivate"} /><button className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">{user.banned ? "Reactivate" : "Deactivate"}</button></form></div></Card>; })}</div></div>;
}
