
import type { Metadata } from "next";
import { ArrowUpRight, FileClock, FileText, ShieldCheck } from "lucide-react";
import { PageIntro } from "@/components/layout/PageIntro";
import { VerificationNote } from "@/components/layout/VerificationNote";
import { Container } from "@/components/ui/Container";
import { Section } from "@/components/ui/Section";
import { knowledgeCollections } from "@/data/knowledge";

export const metadata: Metadata = { title: "Knowledge Centre", description: "Source-labelled institutional references, controlled documents, and cooperative learning resources." };
export default function KnowledgePage() { return <><PageIntro eyebrow="Knowledge and compliance" title="Trusted knowledge needs a source, owner, and version." description="The Knowledge Centre makes publication status visible so users can distinguish an authoritative resource from a planned collection." /><Section><Container><VerificationNote>Legacy documents are never relabelled as RECCU-CAM publications. Each future file should carry a title, issuing authority, effective date, version, and publication status.</VerificationNote><div className="mt-8 grid gap-5 md:grid-cols-2">{knowledgeCollections.map(collection => <article key={collection.slug} className="rounded-3xl border border-gray-200 p-7"><div className="flex items-start justify-between gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-primary-50 text-primary-700">{collection.publicationStatus === "source-available" ? <FileText className="h-6 w-6" /> : <FileClock className="h-6 w-6" />}</span><span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-wider ${collection.publicationStatus === "source-available" ? "bg-primary-50 text-primary-700" : "bg-gray-100 text-gray-600"}`}>{collection.publicationStatus === "source-available" ? "Source available" : "Awaiting publication"}</span></div><h2 className="mt-6 font-display text-xl font-bold text-primary-900">{collection.title}</h2><p className="mt-3 text-sm leading-6 text-gray-600">{collection.description}</p>{collection.href && <a href={collection.href} target="_blank" rel="noreferrer" className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-primary-700">Open source <ArrowUpRight className="h-4 w-4" /></a>}</article>)}</div><div className="mt-10 flex gap-4 rounded-3xl bg-primary-900 p-7 text-white"><ShieldCheck className="h-7 w-7 shrink-0 text-accent-300" /><div><h2 className="font-bold">Controlled publication by design</h2><p className="mt-2 text-sm leading-6 text-primary-100">The preserved admin resource workflow can support future uploads after RECCU-CAM defines approval, review, expiry, and archival responsibilities.</p></div></div></Container></Section></>; }
